version: "3.9"
services:
  web:
    build:
        context: app
        labels:
          owner: "bsm"
          tech: "php"
          app: "hello-world"
    image: hello-php:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html